# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('interval', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('period', models.IntegerField()),
                ('query_date', models.DateField(blank=True)),
                ('returned_trades', models.IntegerField(blank=True)),
            ],
        ),
    ]
